TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += technix.db
DATA += devTechnix.proto

#=======================================
include $(TOP)/configure/RULES
